# Camera source (resolved from cameras.yaml)
camera: "zed_left"

# Topics
visualized_image_topic: "/yolov8_processed_image" # Output topic for visualized images with detection overlays
detection_topic: "/yolov8_detections_output" # Output topic for detection results (Detection2DArray)

# Model and engine file paths
model_file_path: "best.onnx" # The output dimensions must be [1, 5, 8400] (see yolov8_encoder_node.cpp for details)
engine_file_path: "best.engine"

# Visualizer and class names for the visualizer overlay.
enable_visualizer: true
class_names:
  0: "valve"

encoding_desired: "rgb8"

# TensorRT
verbose: true
force_engine_update: false

# ==============================================================================================================================================================
# NOTE: Below wont change unless you change the model architecture or input/output tensor names, so no need to update these if you just swap in a different model
# ==============================================================================================================================================================

# Tensor I/O bindings
input_tensor_names: ["input_tensor"]
input_binding_names: ["images"]
output_tensor_names: ["output_tensor"]
output_binding_names: ["output0"]

# Network
network_image_width: 640
network_image_height: 640
image_mean: [0.0, 0.0, 0.0]
image_stddev: [1.0, 1.0, 1.0]

# Decoder
confidence_threshold: 0.25
nms_threshold: 0.45
num_classes: 1
