name: Build and Push Docker Image

on:
  push:

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Mark repo as safe
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Init submodules and set TERM
        run: |
          git submodule update --init --recursive
          echo "TERM=xterm" >> $GITHUB_ENV

      - name: Build docker images
        run: |
          ./submodules/isaac_ros_common/scripts/build_image_layers.sh -i aarch64.ros2_humble.main
