name: Source Build

on:
  push:

jobs:
  source-build:
    uses: vortexntnu/vortex-ci/.github/workflows/reusable-source-build.yaml@main
    with:
      ros_distro: 'humble'
      os_name: 'ubuntu-22.04'
      ref: ${{ github.ref_name }}
      skip_tests: true
      gcc_version: '13'
