name: Source Build

on:
  workflow_dispatch:
  # Runs daily to check for dependency issues or flaking tests
  schedule:
    - cron: "0 1 * * *"

jobs:
  source-build:
    uses: vortexntnu/vortex-ci/.github/workflows/reusable-source-build.yaml@main
    with:
      ros_distro: 'humble'
      os_name: 'ubuntu-22.04'
      ref: ${{ github.ref_name }}
      vcs_repo_file_url: 'https://raw.githubusercontent.com/vortexntnu/perception-auv/11-task-docker-dev-environment-on-orin/ros2.repos'
